package ru.netology

class VideoAttachment(
    val id: Int,
    val ownerId: Int,
    val title: String,
    val description: String = "",
    val duration: Int,
    val image: List<VideoImage>,
    val firstFrame: List<FirstFrame>,
    val date: Int,
    val addingDate: Int,
    val views: Int,
    val localViews: Int?,
    val comments: Int,
    val player: String,
    val platform: String?,
    val canAdd: Boolean,
    val isPrivate: Boolean?,
    val accessKey: String?,
    val processing: Boolean?,
    val isFavorite: Boolean,
    val canComment: Boolean,
    val canEdit: Boolean,
    val canLike: Boolean,
    val canRepost: Boolean,
    val canSubscribe: Boolean,
    val canAddToFaves: Boolean,
    val canAttachLink: Boolean,
    val width: Int,
    val height: Int,
    val userId: Int,
    val converting: Boolean,
    val added: Boolean,
    val isSubscribed: Boolean,
    val repeat: Int,
    val type: String,
    val balance: Int,
    val liveStatus: String,
    val live: Boolean?,
    val upcoming: Boolean?,
    val spectators: Int,
    val likes: Likes,
    val reposts: VideoReposts
) : SpecificAttachment {

}
